name: BloodFX
main: hoyinm14mc\bloodfx\BloodFX
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11,3.0.0-ALPHA12]
version: 1.1.0
author: hoyinm14mc & CyberCube-HK Team & updated by CupidonSauce173

commands:
  bloodfx:
    usage: /bloodfx help
    permission: bloodfx.command
    description: Command of BloodFX
    aliases: ["blood", "bld"]

permissions:
  bloodfx.command:
    default: op
    children:
      bloodfx.command.set:
        default: op
      bloodfx.command.reload:
        default: op
      bloodfx.command.get:
        default: op
      bloodfx.command.list:
        default: op
      bloodfx.command.on:
        default: op
      bloodfx.command.off:
        default: op
      bloodfx.command.help:
        default: op
